### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PascalPrecht**
Adds article on writing Angular 2 code in ES5

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Ping @timjacobi

**Comment by PascalPrecht** [comment]
Shall I rebase?

**Comment by timjacobi** [comment]
Yes please. Sorry I'm absolutely drowning with work atm.

**Comment by PascalPrecht** [comment]
rebased

**Comment by timjacobi** [comment]
Cheers man. I appreciate it.

**Comment by PascalPrecht** [comment]
You're very welcome. More to come!

**Pull request merged**
